### ISSUE TITLE
Getting this issue when uploading Wifi Profile Mailer

### ISSUE THREAD

**Issue by SamGurdus1** [CedArctic/DigiSpark-Scripts#19]
WiFi_Profile_Mailer_New:9: error: redefinition of 'void loop()'

 void loop() {

      ^

WiFi_Profile_Mailer:7: error: 'void loop()' previously defined here

 void loop() {

      ^

exit status 1
redefinition of 'void loop()'

**Comment by CedArctic** [comment]
Looks like you've defined void loop somewhere else in the script as well or it's in some other file you've imported. Check that you're using the original unmodified file when compiling and that you've followed all instructions correctly here: https://digistump.com/wiki/digispark/tutorials/connecting
I'm closing the issue for now since there doesn't seem to be an issue with the script itself.
